server:
  context-path: /strangler-microservice/v1
  port: 10081
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - text/html
      - text/css
      - application/javascript
      - application/json
spring:
  application:
    name: Strangler Microservice
logging:
  level:
    io.github.georgwittberger.strangler.microservice: DEBUG
cors:
  message:
    allowed-origins:
      - http://localhost:10080
monolith:
  root-url: http://localhost:10080
